/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as ExamesRouteImport } from './routes/exames'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as IndexRouteImport } from './routes/index'

const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesRoute = ExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/contacto': typeof ContactoRoute
  '/exames': typeof ExamesRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/contacto': typeof ContactoRoute
  '/exames': typeof ExamesRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecoes': typeof ColecoesRoute
  '/contacto': typeof ContactoRoute
  '/exames': typeof ExamesRoute
  '/historia': typeof HistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecoes' | '/contacto' | '/exames' | '/historia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecoes' | '/contacto' | '/exames' | '/historia'
  id: '__root__' | '/' | '/colecoes' | '/contacto' | '/exames' | '/historia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecoesRoute: typeof ColecoesRoute
  ContactoRoute: typeof ContactoRoute
  ExamesRoute: typeof ExamesRoute
  HistoriaRoute: typeof HistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames': {
      id: '/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof ExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecoesRoute: ColecoesRoute,
  ContactoRoute: ContactoRoute,
  ExamesRoute: ExamesRoute,
  HistoriaRoute: HistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
